### PR TITLE
fix: Add Orange STB Back To `requiresEncryptionInfoInAllInitSegments`

### LINKED ISSUE #8965: Orange STB Needs To Be Included In `requiresEncryptionInfoInAllInitSegments`
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**

v4.15.9

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
This is webkit based set top box

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Orange STB 6

**What are the manifest and license server URIs?**

I can send them later if needed

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**

Default config with drm

**What did you do?**

Tried to play a multi-period VOD content, with its first period being unencrypted and the 2nd period encrypted. 

**What did you expect to happen?**
I expected playback to start and play both periods without any issues or errors in the console. 

**What actually happened?**

Playback failed with MEDIA_DECODE_ERROR

**Are you planning to send a PR to fix it?**
Yes

### PR DESCRIPTION
**Pull request by agajassi**
Classifies Orange STB as a Webkit STB device and returns true for `requiresEncryptionInfoInAllInitSegments`

Fixes #8965

### CODE REVIEW

File: lib/device/webkit_stb.js [hunk 1]
```diff
@@ -125,6 +141,9 @@ shaka.device.WebKitSTB = class extends shaka.device.AbstractDevice {
    * @private
    */
   static isWebkitSTB_() {
+    if (navigator.userAgent.includes('SOPOpenBrowser')) {
+      return true;
+    }
     if (navigator.userAgent.includes('DT_STB_BCM') ||
         navigator.userAgent.includes('DT_STB_BCM')) {
       return true;
```
Comment (agajassi) [inline lib/device/webkit_stb.js:150]: This looks redundant, 'cos it seems to be comparing the same `DT_STB_BCM` string. Or was the second one meant to be 'Sky' or 'sky'?

Comment (joeyparrish) [reply lib/device/webkit_stb.js:150]: Agreed.  I looked at the history to try to figure out what was meant here, but both lines were added in the same commit (#8210) and they weren't migrated from anywhere else in the repo, so I'm not sure what it's supposed to say on the second string.  @tykus160, you wrote that PR... any guesses what should have been there?

**Review by joeyparrish — APPROVED** [review]
Looks good to me.  If @tykus160 gets back to us quickly with a guess as to what that redundant string should be, we can fix it here.  Otherwise, I'll merge it as is before the end of my Friday (US/Pacific timezone).

File: lib/device/webkit_stb.js (hunk 1 above)
Comment (tykus160) [reply lib/device/webkit_stb.js:150]: Yeah, it looks like a bug from this particular commit https://github.com/shaka-project/shaka-player/pull/8210/commits/4687aa6a5a9f173c862acaaf74f564872e46b9b9#diff-0ad9193ab4fc11f925cead1e0ee98ac1ea43baf8dbd119fd9b7c2e6ed1d09af7
It should be SkyQ. @agajassi if you want to, you can fix it, otherwise I will prepare another PR for that.

**Review by tykus160 — APPROVED** [review]

File: lib/device/webkit_stb.js (hunk 1 above)
Comment (agajassi) [reply lib/device/webkit_stb.js:150]: Thank you guys for confirming. I will just change it to Sky here.

**Comment by agajassi** [comment]
@joeyparrish since @tykus160 confirmed, I updated that part with redundant string. Due to these additional changes, this PR now needs another review.
