### PR TITLE
fix(offline): Speed up offline storage by ~87%

### LINKED ISSUE #4166: Offline downloads are slow
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.3.2

**Can you reproduce the issue with our latest release version?**
Yes, on the 3.3.4 demo site

**Can you reproduce the issue with the latest code from `main`?**
Yes, on the nightly demo site

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome 100/Windows 10

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

On the demo app, I've been using the Sintel content on the main page.
https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

<details>
  <summary>Config object</summary>

From your demo site's `storage.getConfiguration()`, right before the `await storage.store(...)`:

```json
{
    "drm": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000
        },
        "servers": {
            "com.widevine.alpha": "https://cwip-shaka-proxy.appspot.com/no_auth"
        },
        "clearKeys": {},
        "advanced": {
            "com.widevine.alpha": {
                "distinctiveIdentifierRequired": false,
                "persistentStateRequired": false,
                "videoRobustness": "",
                "audioRobustness": "",
                "sessionType": "",
                "serverCertificate": {},
                "serverCertificateUri": "",
                "individualizationServer": ""
            },
            "com.microsoft.playready": {
                "distinctiveIdentifierRequired": false,
                "persistentStateRequired": false,
                "videoRobustness": "",
                "audioRobustness": "",
                "sessionType": "",
                "serverCertificate": {},
                "serverCertificateUri": "",
                "individualizationServer": ""
            },
            "com.apple.fps": {
                "distinctiveIdentifierRequired": false,
                "persistentStateRequired": false,
                "videoRobustness": "",
                "audioRobustness": "",
                "sessionType": "",
                "serverCertificate": {},
                "serverCertificateUri": "",
                "individualizationServer": ""
            },
            "com.adobe.primetime": {
                "distinctiveIdentifierRequired": false,
                "persistentStateRequired": false,
                "videoRobustness": "",
                "audioRobustness": "",
                "sessionType": "",
                "serverCertificate": {},
                "serverCertificateUri": "",
                "individualizationServer": ""
            },
            "org.w3.clearkey": {
                "distinctiveIdentifierRequired": false,
                "persistentStateRequired": false,
                "videoRobustness": "",
                "audioRobustness": "",
                "sessionType": "",
                "serverCertificate": {},
                "serverCertificateUri": "",
                "individualizationServer": ""
            }
        },
        "delayLicenseRequestUntilPlayed": false,
        "logLicenseExchange": false,
        "updateExpirationTime": 1,
        "preferredKeySystems": []
    },
    "manifest": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000
        },
        "availabilityWindowOverride": null,
        "disableAudio": false,
        "disableVideo": false,
        "disableText": false,
        "disableThumbnails": false,
        "defaultPresentationDelay": 0,
        "dash": {
            "clockSyncUri": "https://shaka-player-demo.appspot.com/time.txt",
            "ignoreDrmInfo": false,
            "disableXlinkProcessing": false,
            "xlinkFailGracefully": false,
            "ignoreMinBufferTime": false,
            "autoCorrectDrift": true,
            "initialSegmentLimit": 1000,
            "ignoreSuggestedPresentationDelay": false,
            "ignoreEmptyAdaptationSet": false,
            "ignoreMaxSegmentDuration": false,
            "keySystemsByURI": {
                "urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b": "org.w3.clearkey",
                "urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed": "com.widevine.alpha",
                "urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
                "urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready",
                "urn:uuid:f239e769-efa3-4850-9c16-a903c6932efb": "com.adobe.primetime"
            }
        },
        "hls": {
            "ignoreTextStreamFailures": false,
            "ignoreImageStreamFailures": false,
            "useFullSegmentsForStartTime": false,
            "defaultAudioCodec": "mp4a.40.2",
            "defaultVideoCodec": "avc1.42E01E"
        }
    },
    "streaming": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000
        },
        "rebufferingGoal": 2,
        "bufferingGoal": 10,
        "bufferBehind": 30,
        "ignoreTextStreamFailures": false,
        "alwaysStreamText": false,
        "startAtSegmentBoundary": false,
        "gapDetectionThreshold": 0.1,
        "smallGapLimit": 0.5,
        "jumpLargeGaps": false,
        "durationBackoff": 1,
        "forceTransmuxTS": false,
        "safeSeekOffset": 5,
        "stallEnabled": true,
        "stallThreshold": 1,
        "stallSkip": 0.1,
        "useNativeHlsOnSafari": true,
        "inaccurateManifestTolerance": 2,
        "lowLatencyMode": false,
        "autoLowLatencyMode": false,
        "forceHTTPS": false,
        "preferNativeHls": false,
        "updateIntervalSeconds": 1,
        "dispatchAllEmsgBoxes": false,
        "observeQualityChanges": false
    },
    "offline": {
        "usePersistentLicense": true
    },
    "abr": {
        "enabled": true,
        "useNetworkInformation": true,
        "defaultBandwidthEstimate": 1000000,
        "switchInterval": 8,
        "bandwidthUpgradeTarget": 0.85,
        "bandwidthDowngradeTarget": 0.95,
        "restrictions": {
            "minWidth": 0,
            "maxWidth": null,
            "minHeight": 0,
            "maxHeight": null,
            "minPixels": 0,
            "maxPixels": null,
            "minFrameRate": 0,
            "maxFrameRate": null,
            "minBandwidth": 0,
            "maxBandwidth": null
        },
        "advanced": {
            "minTotalBytes": 128000,
            "minBytes": 16000,
            "fastHalfLife": 2,
            "slowHalfLife": 5
        }
    },
    "preferredAudioLanguage": "en%3Btextlang%3Den%3Builang%3Den%3Bpanel%3DHOME%3Bbuild%3Dcompiled",
    "preferredTextLanguage": "en",
    "preferredVariantRole": "",
    "preferredTextRole": "",
    "preferredAudioChannelCount": 2,
    "preferredVideoCodecs": [],
    "preferredAudioCodecs": [],
    "preferForcedSubs": false,
    "preferredDecodingAttributes": [],
    "restrictions": {
        "minWidth": 0,
        "maxWidth": null,
        "minHeight": 0,
        "maxHeight": null,
        "minPixels": 0,
        "maxPixels": null,
        "minFrameRate": 0,
        "maxFrameRate": null,
        "minBandwidth": 0,
        "maxBandwidth": null
    },
    "playRangeStart": 0,
    "playRangeEnd": null,
    "cmcd": {
        "enabled": false,
        "sessionId": "",
        "contentId": "",
        "useHeaders": false
    }
}
```
</details>

**What did you do?**

On the Shaka demo site, I opened the Chrome dev tools, cleared the network tab, and clicked the download button for Sintel.

**What did you expect to happen?**
I expected the transfer to download fairly quickly, ideally using all the available bandwidth. For reference, using `wget`, I can download a webm track from Sintel at around 27.25MB/s (or 218 Mbit/s, which is about the limit of my connection).

```bash
wget --report-speed=bits -O /dev/null https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/v
-0576p-1000k-vp9.webm
```

**What actually happened?**

Once the download via Shaka completed, I took the MB transferred from the Chrome dev tools network page (91.6MB), divided by the last request's start time (33.39 seconds for me), and got 2.74 MB/s (or 21.95Mbit/s) to get a rough estimate. (I also verified that the MPD request was queued at 0ms so I could in theory trust the dev tool timings.) In our custom app, we do calculate an estimated download speed, which is in the same ballpark as Sintel, but for our own content/CDN.

Since Shaka is downloading each byte range as a separate request, I don't expect it to be able to match the throughput of `wget`, but I wasn't expecting it to be ~10x slower.

We've also tested our own content being served from the same network (1Gb/s theoretical speeds), and we're still only downloading at around 13MB/s (or 104Mbit/s), so again about 10x below theoretical maxes.

It looks like Shaka is downloading each byte range serially, with the only parallelism being the unique files it's downloading (each audio track and video track will happen in parallel). Eventually though, the download will have completed all the audio tracks and low bitrate video tracks leaving one file still downloading, and it'll only be requesting one byte range at a time. Since there's no ability to pause or resume a download in Shaka, this is pretty inconvenient when downloading a large video, such as a movie.

Also, for more context, I went to YouTube and downloaded a video in the web app with YouTube Premium, which seemed to download at around 9MB/s (or 73Mbit/s). Their downloads are serially transferred as well, yet several times faster. YouTube may have larger segments to reduce each request's overhead. I also realize that YouTube is likely not using Shaka Player at all, so it's comparing apples to oranges.

Is this the expected behavior? Is there a bug preventing faster downloads? Would it even be possible to download multiple byte ranges in parallel for the same track/file?

### PR DESCRIPTION
**Pull request by joeyparrish**
By waiting for all segment data to be written to the database before updating the manifest, we can speed up offline storage in the foreground by ~87%.

Closes #4166

### CODE REVIEW

File: lib/offline/storage.js [hunk 1]
```diff
@@ -561,11 +576,6 @@ shaka.offline.Storage = class {
...
       activeHandle = await muxer.getActive();
 
-      // Store the data.
-      const dataKeys = await activeHandle.cell.addSegments([data]);
-      dataKey = dataKeys[0];
-      throwIfAbortedFn();
-
       // Acquire the mutex before accessing the manifest, since there could be
       // multiple instances of this method running at once.
       mutexId = await shaka.offline.Storage.mutex_.acquire();
```
Comment (theodab) [inline lib/offline/storage.js:581]: I don't think we need this mutex anymore? Since any given store operation is only going to be running this method once or twice anyway, and in the two-calls case they definitely don't happen at the same time. So there's no risk of a given storage entry being mutated by two different threads at once.

And if we get rid of this mutex, we could get rid of the `shaka.util.Mutex` class too.

File: lib/offline/storage.js [hunk 2]
```diff
@@ -538,19 +554,18 @@ shaka.offline.Storage = class {
...
-   * @param {!shaka.media.SegmentReference} ref
-   * @param {shaka.extern.SegmentDataDB} data
+   * @param {!Object.<string, number>} manifestUpdates
+   * @param {number} dataSizeUpdate
    * @param {function()} throwIfAbortedFn  A function that should throw if the
    *   download has been aborted.
    * @return {!Promise.<?shaka.extern.ManifestDB>}
    */
-  static async assignStreamToManifest(manifestId, ref, data, throwIfAbortedFn) {
+  static async assignStreamToManifest(
```
Comment (theodab) [inline lib/offline/storage.js:563]: Nit: The method should probably be called `assignStreamsToManifest` now that it can do multiple at once.

**Review by theodab — CHANGES_REQUESTED** [review]

File: lib/offline/storage.js (hunk 2 above)
Comment (joeyparrish) [reply lib/offline/storage.js:563]: Renamed to assignSegmentsToManifest, since it is now only setting the database keys of the segments.  The streams are already part of the manifest.

File: lib/offline/storage.js (hunk 1 above)
Comment (joeyparrish) [reply lib/offline/storage.js:581]: Removed Mutex.

File: lib/offline/storage.js [hunk 3]
```diff
@@ -538,19 +554,18 @@ shaka.offline.Storage = class {
    * changes of the other.
    *
    * @param {number} manifestId
-   * @param {!shaka.media.SegmentReference} ref
-   * @param {shaka.extern.SegmentDataDB} data
+   * @param {!Object.<string, number>} manifestUpdates
```
[the remark this answers is not in the document]
Comment (joeyparrish) [reply lib/offline/storage.js:557]: Docs updated.

File: lib/offline/storage.js [hunk 4]
```diff
@@ -441,36 +441,34 @@ shaka.offline.Storage = class {
   async downloadSegments_(
       toDownload, manifestId, manifestDB, downloader, config, storage,
       manifest, drmEngine) {
+    let pendingManifestUpdates = {};
```
[the remark this answers is not in the document]
Comment (joeyparrish) [reply lib/offline/storage.js:444]: I think that what would happen now is:

1. Downloaded segments are stored in the database
2. Those segments are orphaned and not referred to in any manifest

That can also happen if the user closes the page, though.

Let me look at two things in a follow-up:

1. How to deal with orphaned segments (which can happen without cancellation)
2. How to clean up segments in the same session on abort()

**Review by theodab — DISMISSED** [review]

File: lib/offline/storage.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (theodab) [reply lib/offline/storage.js:443]: Sounds good.

**Comment by joeyparrish** [comment]
Bah, linter failed!  Fixed now, but sadly, I'll need another approval.

**Review by theodab — APPROVED** [review]
