### PR TITLE
fix(CEA): reset PTS on new init segment

### LINKED ISSUE #6605: Closed Captions from main content appear in the end of midroll
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

N/A

**What version of Shaka Player are you using?**

Custom fork

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Own

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
MacOS Chrome, Samsung, LG.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default one

**What did you do?**

Played DASH multiperiod stream and enabled embedded captions.

**What did you expect to happen?**
Captions should appear on main content, but not on ads.

**What actually happened?**

Our streams have captions embedded on main content, but not on ads. However, at last seconds of midroll subtitles from main content are starting to appear with ridiculously low start time, which matches end time from last cue before ads.

**Are you planning send a PR to fix it?**
Yes

### PR DESCRIPTION
**Pull request by tykus160**
Fixes #6605
Resets cache (including last used presentation timestamp) of CEA Decoder on every init segment append.
Adds few debug logs to easify investigations in the future.

### CODE REVIEW

**Review by avelad — APPROVED** [review]

**Review by theodab — APPROVED** [review]

File: lib/media/closed_caption_parser.js [hunk 1]
```diff
@@ -88,6 +90,10 @@ shaka.media.ClosedCaptionParser = class {
    * @override
    */
   init(initSegment) {
+    shaka.log.debug('Passing new init segment to CEA parser');
+    // Reset underlying decoder when new init segment arrives
+    // to clear stored pts values.
+    this.reset();
```
Comment (caridley) [inline lib/media/closed_caption_parser.js:96]: Will this cause undesirable behavior on a bit-rate change?

Comment (joeyparrish) [reply lib/media/closed_caption_parser.js:96]: Can you be more specific?  It seems to be the explicit intent of the author to reset CEA decoding when we switch bitrates (append init segment).  What undesirable behavior are you seeing / anticipating?

Comment (caridley) [reply lib/media/closed_caption_parser.js:96]: i think they need to distinguish period change from bitrate change.

Comment (avelad) [reply lib/media/closed_caption_parser.js:96]: Yes, you are right. @caridley can you send a PR to fix it?

Comment (caridley) [reply lib/media/closed_caption_parser.js:96]: I don't think I will have time to do that. Sorry

Comment (avelad) [reply lib/media/closed_caption_parser.js:96]: I have a fix for it, https://github.com/shaka-project/shaka-player/pull/6671
