### PR TITLE
fix: Fix config failures with multiple references to an input array

### LINKED ISSUE #8478: config.drm.advanced.*.videoRobustness will be emptied if a variable is referred more than once
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**
Not about FairPlay

**What version of Shaka Player are you using?**
4.14.8

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Not tried yet

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
No

**What browser and OS are you using?**
Edge on Windows

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
Any URIs supporting PlayReady SL3000 can reproduce the issue

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**
```js
    const advanced = {
        videoRobustness: ['3000'],
    };
    const config = {
        drm: {
            servers: {
                'com.microsoft.playready': licenseUri,
                'com.microsoft.playready.recommendation': licenseUri,
            },
            advanced: {
                'com.microsoft.playready': advanced,
                'com.microsoft.playready.recommendation': advanced,
                // 'com.microsoft.playready.recommendation': structuredClone(advanced), // workaround
            },
        },
        manifest: {
            dash: {
                keySystemsByURI: {
                    'urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95': 'com.microsoft.playready.recommendation',
                    'urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95': 'com.microsoft.playready.recommendation',
                },
            },
        },
    };
    const player = new shaka.Player();
    player.configure(config);
    await player.attach(document.querySelector('video'));
    await player.load(contentUri);
    console.debug(player.getConfiguration().drm.advanced['com.microsoft.playready.recommendation']);
```

**What did you do?**
Written above

**What did you expect to happen?**
console.debug(...) outputs
```js
{ ..., videoRobustness: ['3000'] }
```

**What actually happened?**
Outputs
```js
{ .., videoRobustness: [] }
```
and shaka-player error log
`Invalid config, wrong type for .drm.advanced.com.microsoft.playready.recommendation.videoRobustness` at config_utils.js:97

Then, license error occurs due to insufficient Security Level

**Are you planning to send a PR to fix it?**
Currently no, using structuredClone() works around this

### PR DESCRIPTION
**Pull request by joeyparrish**
When the user passes an array-based config, we should never copy the reference.  Instead, we should clone the array.  This way, changes to that outside array don't immediately affect the running config.

Closes #8478

### CODE REVIEW

File: lib/util/config_utils.js [hunk 1]
```diff
@@ -101,6 +101,10 @@ shaka.util.ConfigUtils = class {
         shaka.log.alwaysWarn(
             'Unexpected number of arguments for ' + subPath);
         destination[k] = source[k];
+      } else if (Array.isArray(destination[k])) {
+        // Make a copy of the input array, so that changes to the source object
+        // don't immediately affect the running config.
+        destination[k] = source[k].slice();
```
Comment (littlespex) [inline lib/util/config_utils.js:107]: Do the array items need to be cloned as well?

Comment (joeyparrish) [reply lib/util/config_utils.js:107]: Right now, they are all arrays of strings.

File: lib/util/config_utils.js [hunk 2]
```diff
@@ -101,6 +101,13 @@ shaka.util.ConfigUtils = class {
         shaka.log.alwaysWarn(
             'Unexpected number of arguments for ' + subPath);
         destination[k] = source[k];
+      } else if (Array.isArray(destination[k])) {
+        // Make a copy of the input array, so that changes to the source object
+        // don't immediately affect the running config.
+        // Since everything here is very loosely-typed, use a cast to convince
+        // the compiler we're not calling slice() on a potential ArrayBuffer,
+        // which would break Tizen.
+        destination[k] = /** @type {Array} */(source[k]).slice();
```
Comment (TAhub) [inline lib/util/config_utils.js:110]: If you put `Array.isArray(source[k])` into the condition, does it solve this issue without needing to do a cast? `Array.isArray` does return false for ArrayBuffers, but I'm not sure if the compiler understands the implications of `Array.isArray` returning true.

**Review by TAhub — CHANGES_REQUESTED** [review]

File: lib/util/config_utils.js (hunk 2 above)
Comment (joeyparrish) [reply lib/util/config_utils.js:110]: Nope.  "The type information available for this expression is too loose to ensure conformance."

Comment (TAhub) [reply lib/util/config_utils.js:110]: That's a shame.

**Review by TAhub — APPROVED** [review]

**Review by avelad — APPROVED** [review]
