### PR TITLE
fix: Fix playRangeEnd for certain content

### LINKED ISSUE #4026: Play Range start and end settings
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.3.2

**Can you reproduce the issue with our latest release version?**
NO

**Can you reproduce the issue with the latest code from `main`?**
NO

**Are you using the demo app or your custom app?**
Demo APP

**If custom app, can you reproduce the issue using our demo app?**
__

**What browser and OS are you using?**
Chrome, Firefox, safari edge on iOS, iPadOS, macOS, Linux, windows

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://dash.akamaized.net/akamai/bbb_30fps/bbb_with_tiled_thumbnails.mpd
https://multiplatform-f.akamaihd.net/i/multi/will/bunny/big_buck_bunny_,640x360_400,640x360_700,640x360_1000,950x540_1500,.f4v.csmil/master.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

playRangeStart: 10,
playRangeEnd: 100

**What did you do?**

I try to set the start and end range for a VOD

**What did you expect to happen?**
To have a timeline same as start and end range declared

**What happened?**

When I try to apply the play range start and end for DASH, I have a perfect timeline UI with the range declared, but the video is stuck and doesn't play further unless I click the timeline it plays than when I take back the seek to the start it Stops again.
DASH

FOR HLS, 
When we declare the range the UI is not well set up and when the video ends we are not able to play the video again.

HLS

For mp4, the settings are not applied.

Thanks

### PR DESCRIPTION
**Pull request by joeyparrish**
For content where the manifest parser uses the notifySegments API
(DASH SegmentBase/SegmentList/SegmentTimeline, or HLS, but not DASH
SegmentTemplate+duration), the Player seekRangeEnd configuration was
not being honored correctly.

This fixes the issue in PresentationTimeline and adds a regression
test to our playRangeStart/playRangeEnds tests.

Fixed #4026

### CODE REVIEW

File: lib/media/presentation_timeline.js [hunk 1]
```diff
@@ -361,6 +361,13 @@ shaka.media.PresentationTimeline = class {
   getSegmentAvailabilityEnd() {
```
Comment (theodab) [inline lib/media/presentation_timeline.js:361]: The JSDoc for the return value, above, says "Aways returns the presentation's duration for video-on-demand." That seems to be pretty out-of-date, now.

File: lib/media/presentation_timeline.js [hunk 2]
```diff
@@ -361,6 +361,13 @@ shaka.media.PresentationTimeline = class {
...
     if (!this.isLive() && !this.isInProgress()) {
       // It's a static manifest (can also be a dynamic->static conversion)
+      if (this.maxSegmentEndTime_ && this.duration_) {
```
Comment (theodab) [inline lib/media/presentation_timeline.js:364]: Do we care about the possibility of `duration_` or `maxSegmentEndTime_` being 0 here?

If not, you don't need to check if `duration_` is truthy, because it's a non-nullable number and it initializes to Infinity.

File: test/player_unit.js [hunk 3]
```diff
@@ -703,6 +704,39 @@ describe('Player', () => {
       expect(seekRange.end).toBe(10);
     });
 
+    // Test for https://github.com/shaka-project/shaka-player/issues/4026
+    it('configures play and seek range with notifySegments', async () => {
+      player.configure({playRangeStart: 5, playRangeEnd: 10});
+      const timeline = new shaka.media.PresentationTimeline(300, 0);
+      timeline.setStatic(true);
+      timeline.setDuration(300);
```
Comment (theodab) [inline test/player_unit.js:712]: It's a bit confusing how in this test, `playRangeEnd` corresponds with `duration_` inside the timeline, and the `setDuration` method call corresponds with `maxSegmentEndTime_` in the timeline. Feels like the two things named duration should match up.
That's out of the scope of this CL though.

**Review by theodab — CHANGES_REQUESTED** [review]

File: lib/media/presentation_timeline.js (hunk 1 above)
Comment (joeyparrish) [reply lib/media/presentation_timeline.js:361]: Fixed.  Thanks!

File: lib/media/presentation_timeline.js (hunk 2 above)
Comment (joeyparrish) [reply lib/media/presentation_timeline.js:364]: Ah, true.  Fixed.

File: test/player_unit.js (hunk 3 above)
Comment (joeyparrish) [reply test/player_unit.js:712]: Yeah, it's weird.  What's really happening is that stream.useSegmentTemplate refers to timeline's duration to decide how many references to generate.  Then player.load applies the config to the timeline, and sets the duration lower.

What would be less confusing, I think, is if Timeline had a separate field for the playRangeEnd setting.  But that would also require a lot more ifs or mins in Timeline, which could be confusing in a different way.

**Review by theodab — APPROVED** [review]
