### PR TITLE
fix: Fix exiting fullscreen on Safari

### LINKED ISSUE #5437: TypeError: screen.orientation.unlock() is not a function
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.6

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
MacOS Ventura 13.4.1, Safari Version 16.5.2 (18615.2.9.11.10)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
/

**What are the manifest and license server URIs?**

Not important

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Not important

**What did you do?**
Play a random video.
Clicked on Fullscreen Button
Entered Fullscreen
Clicked on fullscreen button again

**What did you expect to happen?**
Leave Fullscreen

**What actually happened?**
Stayed in fulscreen. Found error on console: 
Unhandled Promise Rejection: TypeError: screen.orientation.unlock is not a function. (In 'screen.orientation.unlock()', 'screen.orientation.unlock' is undefined) 
on fullscreen_button.js: 57

The bug is not present on any other desktop browser. It seems caused by the unavailability of the ScreenOrientation lock() and unlock() methods on safari ( 
https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/unlock 
https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/lock
)

For reference, it seems to be close to #3907 but on this case the player actually has a negative effect.

### PR DESCRIPTION
**Pull request by theodab**
`screen.orientation.unlock` is not defined on Safari, even though `screen.orientation` is.
This changes our orientation polyfill to add that method to `screen.orientation`.

Fixes #5437

### CODE REVIEW

**Comment by WINOFFRG** [comment]
Hey @theodab With this should we even extend and patch the existing [Orientation Polyfill](https://shaka-player-demo.appspot.com/docs/api/shaka.polyfill.Orientation.html) with reference from https://github.com/chmanie/o9n#supported-browsers?

**Comment by theodab** [comment]
> Hey @theodab With this should we even extend and patch the existing [Orientation Polyfill](https://shaka-player-demo.appspot.com/docs/api/shaka.polyfill.Orientation.html) with reference from https://github.com/chmanie/o9n#supported-browsers?

I guess updating the polyfill would be nicer, you're right. It looks like that polyfill [just falls through to a no-op](https://github.com/chmanie/o9n/blob/f0da290b13214330c29de28e489baf28f189ca51/index.js#L195-L197) for Safari, so I'm not sure if it will be very relevant here as a reference though.

**Comment by WINOFFRG** [comment]
Yes it's a noop for Safari, Reason for patching the polyfill as on custom apps the developers even noticing that an Orientation Polyfill exists but still it fails to handle it on Safari.

File: lib/polyfill/orientation.js [hunk 1]
```diff
@@ -23,21 +24,47 @@ shaka.polyfill.Orientation = class {
...
+  /**
+   * Modifies screen.orientation to add no-ops for missing methods.
+   * Meant for cases where screen.orientation is defined, but has missing
+   * methods that cannot be properly polyfilled.
+   * @private
+   */
+  static installBasedOnScreenMethods_() {
+    if (screen.orientation.lock === undefined) {
+      screen.orientation.lock = (orientation) => {
+        shaka.log.info('screen.orientation.lock is a no-op');
```
Comment (joeyparrish) [inline lib/polyfill/orientation.js:57]: What happens when this no-op is used?  How does the app behavior differ from the normal case?

File: lib/polyfill/orientation.js [hunk 2]
```diff
@@ -23,21 +24,47 @@ shaka.polyfill.Orientation = class {
...
+        return Promise.resolve();
+      };
+    }
+    if (screen.orientation.unlock === undefined) {
+      screen.orientation.unlock = () => {
+        shaka.log.info('screen.orientation.unlock is a no-op');
```
Comment (joeyparrish) [inline lib/polyfill/orientation.js:63]: Same question here.

**Review by joeyparrish — COMMENTED** [review]
It's not clear to me how this fixes exiting fullscreen.  If we're already called orientation.lock(), how is okay to skip unlock()?

File: lib/polyfill/orientation.js (hunk 1 above)
Comment (theodab) [reply lib/polyfill/orientation.js:57]: Well, this no-op doesn't change anything because we already wrap the `lock` method in a try-catch to silence errors. I just included it for sake of completeness.

File: lib/polyfill/orientation.js (hunk 2 above)
Comment (theodab) [reply lib/polyfill/orientation.js:63]: This one improves things because, on desktop Safari, neither `lock` nor `unlock` are implemented. So we don't need to unlock the screen, because we never locked it in the first place; we just need to prevent the method call from erroring, so that we can move on to the part of the code that calls `document.exitFullscreen`.
I guess technically this approach, where each methods is filled with a no-op independently, would lead to a weird result if the browser has `lock` implemented but doesn't have `unlock` implemented. But I would hope that no browser provides an API for locking the screen without providing an API for unlocking it, that sounds like an accident waiting to happen.

Comment (joeyparrish) [reply lib/polyfill/orientation.js:63]: I had the impression from this PR and the comments on it that only unlock() was missing on Safari.  Thanks for clarifying.

**Review by joeyparrish — APPROVED** [review]
