### PR TITLE
fix: Disable seek retry cooldown on most platforms

### LINKED ISSUE #4393: Playback is broken after seeking to video end
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes. The issue is similar to #1967 and #1014.

**What version of Shaka Player are you using?**
4.1.2 & 3.1.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome 102.0.5005.63 and Firefox 100.0.2. Windows 10

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
Manifest: https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd
I have been able to reproduce the issue with all manifests tested.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Default config, but I am able to also reproduce it programmatically if `streaming.durationBackoff` is set to `0`.

**What did you do?**
Seek to the duration of the video. Note: You need to drag the slider past the end.
Seek to somewhere else.
Start playback.

**What did you expect to happen?**
Playback is working.

**What actually happened?**
Playback is not working. In Chrome when clicking play the play head will jump to the end. In Firefox you cannot seek. The play head jumps to the start.

### LINKED ISSUE #5202: Possible to seek beyond live edge. Not corrected
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.5

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app, but also reproduced in demo

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Various, but reproduced on Windows Chrome with the demo app

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
Reproduced with "Live Sim (2s segments)"

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Reproduced with default config

**What did you do?**
Seek beyond the seekable range, wait half a second, then do it again
```
const vidEl = document.getElementById("video");
vidEl.currentTime = vidEl.currentTime + 3600; 
setTimeout(()=>{vidEl.currentTime = vidEl.currentTime + 3600;}, 500);
```

**What did you expect to happen?**
The video to play from the live edge

**What actually happened?**
The player got stuck waiting.
I also tried seeking a smaller amount into the future (1 minute), and it recovered and started playing after a minute

The problem seems to be in `MediaSourcePlayhead.onSeeking_()` https://github.com/shaka-project/shaka-player/blob/a8e3c9ab310b14ca71610c568cffe108b30d38bf/lib/media/playhead.js#L409

The first seek out of range is corrected, but because the next happens within a second, the correction is simply discarded.

### PR DESCRIPTION
**Pull request by theodab**
Previously, we added a 1 second "cooldown" period between attempts to perform a corrective seek.
This was for the benefit of old v1 Chromecasts, which found the process of seeking so slow that they would sometimes get stuck in an infinite loop trying to start a presentation.
However, that cooldown period was causing issues in some situations during seeking, so this PR removes the restriction on everything but pre-Android Chromecast devices.

Fixes #4393
Fixes #5202

### CODE REVIEW

File: lib/util/platform.js [hunk 1]
```diff
@@ -645,6 +645,25 @@ shaka.util.Platform = class {
...
+  /**
+   * On some platforms, such as v1 Chromecasts, the act of seeking can take a
+   * significant amount of time.
+   *
+   * @return {boolean}
+   */
+  static isSeekingSlow() {
+    const Platform = shaka.util.Platform;
+    if (Platform.isChromecast()) {
+      if (Platform.isAndroidCastDevice()) {
```
Comment (avelad) [inline lib/util/platform.js:657]: And Fuchsia?

**Comment by avelad** [comment]
@shaka-bot test

File: lib/util/platform.js (hunk 1 above)
Comment (theodab) [reply lib/util/platform.js:657]: For reference...
I didn't have a Fuchsia device to test with, so I can't say for sure it's not a problem in them. It's probably fine, I was just being purposefully conservative with this change.
