### PR TITLE
fix: Missing AES-128 key of last HLS segment

### LINKED ISSUE #4517: Fetching last segment of HLS AES-128 stream fails
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.2.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
macOS Monterey 12.6
Chrome 105.0.5195.125 (arm64)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
"Art of Motion (HLS, TS, AES-128)" on the Shaka Player Demo page

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
The configuration of the demo page

**What did you do?**
Tried to play the video until the end

**What did you expect to happen?**
Video is played to the end without issues

**What actually happened?**
An error 3018(`MEDIA.TRANSMUXING_FAILED`) occurs when fetching the last segment,
and never-ending loading begins when attempting to play the last segment.

### PR DESCRIPTION
**Pull request by devsunb**
Closes #4517

## Problem

Fetching the last segment of HLS AES-128 stream fails with 3018 error
- `MediaSourceEngine` attempts to transmux encrypted TS data
- `StreamingEngine` does not decrypt TS data of the last segment
- `SegmentReference` of the last segment has `null` for `hlsAes128Key`
- `hlsAes128Key` is missing when adjusting the last SegmentReference in `SegmentIndex.fit()`

### CODE REVIEW

**Comment by avelad** [comment]
@theodab can you review it? You are the expert in AES-128

File: test/media/segment_index_unit.js [hunk 1]
```diff
@@ -955,9 +955,11 @@ describe('SegmentIndex', /** @suppress {accessControls} */ () => {
    * @param {number} startTime
    * @param {number} endTime
    * @param {!Array.<!shaka.media.SegmentReference>=} partialReferences
+   * @param {!shaka.extern.HlsAes128Key} hlsAes128Key
```
Comment (joeyparrish) [inline test/media/segment_index_unit.js:958]: nit: If this is an optional parameter, the type should end with an equals sign to signify that.

File: test/media/segment_index_unit.js [hunk 2]
```diff
@@ -955,9 +955,11 @@ describe('SegmentIndex', /** @suppress {accessControls} */ () => {
...
    * @return {shaka.media.SegmentReference}
    */
-  function makeReference(uri, startTime, endTime, partialReferences = []) {
+  function makeReference(uri, startTime, endTime, partialReferences = [],
+      hlsAes128Key = {method: 'AES-128', firstMediaSequenceNumber: 0}) {
```
Comment (joeyparrish) [inline test/media/segment_index_unit.js:962]: Do we want to default that to non-null at all times in all tests?

Could you instead make a regression test for this particular bug, where you show that hlsAes128Key is preserved on the last segment after a fit() call?

**Review by joeyparrish — CHANGES_REQUESTED** [review]

**Comment by avelad** [comment]
@devsunb can you rebase to resolve the issues in the tests? Thank you!

File: test/media/segment_index_unit.js (hunk 1 above)
Comment (devsunb) [reply test/media/segment_index_unit.js]: Thank you for your review. I fixed it!

File: test/media/segment_index_unit.js (hunk 2 above)
Comment (devsunb) [reply test/media/segment_index_unit.js]: Done!

Comment (devsunb) [reply test/media/segment_index_unit.js]: ## Before



## After

File: lib/media/segment_index.js [hunk 3]
```diff
@@ -364,7 +364,10 @@ shaka.media.SegmentIndex = class {
             lastReference.partialReferences,
             lastReference.tilesLayout,
             lastReference.tileDuration,
-            lastReference.syncTime);
+            lastReference.syncTime,
+            undefined,
```
Comment (avelad) [inline lib/media/segment_index.js:368]: Please add `/* status= */ shaka.media.SegmentReference.Status.AVAILABLE` (the default value in the constructor of shaka.media.SegmentReference)

**Review by avelad — CHANGES_REQUESTED** [review]

File: lib/media/segment_index.js (hunk 3 above)
Comment (devsunb) [reply lib/media/segment_index.js]: Done!

**Review by avelad — APPROVED** [review]

**Review by daraqui — DISMISSED** [review]

**Comment by devsunb** [comment]
> @devsunb please fix the linter errors, thanks!

I fixed it! Sorry for my oversight.

**Review by avelad — DISMISSED** [review]

File: lib/media/segment_index.js [hunk 4]
```diff
@@ -364,7 +364,10 @@ shaka.media.SegmentIndex = class {
             lastReference.partialReferences,
             lastReference.tilesLayout,
             lastReference.tileDuration,
-            lastReference.syncTime);
+            lastReference.syncTime,
+            /* status= */ shaka.media.SegmentReference.Status.AVAILABLE,
```
Comment (joeyparrish) [inline lib/media/segment_index.js:368]: Should be lastReference.status AFAICT

**Review by joeyparrish — CHANGES_REQUESTED** [review]

**Review by joeyparrish — APPROVED** [review]

**Comment by joeyparrish** [comment]
Thanks for your contribution!  I'll merge this after the new test run is complete.
