### PR TITLE
fix: Fix drm.keySystemsMapping config

### LINKED ISSUE #4422: keySystemsMapping unrecognized
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**

4.2.0

**Can you reproduce the issue with our latest release version?**

yes

**Can you reproduce the issue with the latest code from `main`?**

yes

**Are you using the demo app or your own custom app?**

custom

**If custom app, can you reproduce the issue using our demo app?**

Have not tried

**What browser and OS are you using?**

macOS chrome
Windows Edge

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

tried to add keySystemsMapping to DRM config
```
player.configure({
  drm: {
    keySystemsMapping: {
      'com.microsoft.playready': 'com.microsoft.playready.recommendation',
    }
  }
});
```

**What did you expect to happen?**

To have the keysystemsmapping not be empty in my player.getconfiguration

**What actually happened?**

Getting a console response
`Invalid config, unrecognized key .drm.keySystemsMapping.com.microsoft.playready`

player.getconfiguration
`preferredKeySystems":[],"keySystemsMapping":{}},`

### PR DESCRIPTION
**Pull request by joeyparrish**
This fixes the config by adding a missing override in the config parser.  This also adds test coverage for the feature.

Closes #4422

### CODE REVIEW

**Review by theodab — APPROVED** [review]

File: test/media/drm_engine_unit.js [hunk 1]
```diff
@@ -677,6 +677,35 @@ describe('DrmEngine', () => {
...
+
+      config.keySystemsMapping['drm.abc'] = 'drm.def';
+      drmEngine.configure(config);
+
+      const variants = manifest.variants;
+      await expectAsync(
+          drmEngine.initForPlayback(variants, manifest.offlineSessionIds))
+          .toBeRejected();
+
+      expect(drmEngine.initialized()).toBe(false);
```
Comment (JulianDomingo) [inline test/media/drm_engine_unit.js:700]: FMI, this scenario is set to fail DRM initialization because in L690, it was set to fail all key systems? 

But even then, it still reaches these lines: https://github.com/shaka-project/shaka-player/blob/c935cc17703297a44b3ce3bda75d8f2ea37f4147/lib/media/drm_engine.js#L351-L361 which is why L701-705 show the decodingInfoSpy is called with the mapping information?

**Review by JulianDomingo — APPROVED** [review]
