### PR TITLE
fix: PERIOD_FLATTENING_FAILED error when periods have different base sample types.

### LINKED ISSUE #4202: PERIOD_FLATTENING_FAILED Error when playing mixed hvc1/hev1 or dvhe/dvh1 periods.
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Sahak 4.0.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo

**If custom app, can you reproduce the issue using our demo app?**
n/a

**What browser and OS are you using?**
Chrome or Safari.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**
https://storage.googleapis.com/trumantest-public/gh/shaka-bug.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
demo page config.

**What did you do?**
Attempt to play https://storage.googleapis.com/trumantest-public/gh/shaka-bug.mpd.

**What did you expect to happen?**
The stream should play properly.
It does actually play properly when I edit the mpd to only have dvh/hvc1 periods instead of a mix.

**What actually happened?**
The console shows the following error:
"Unused stream in period-flattening!"
... codecs: "dvh1.05.01" ....

### PR DESCRIPTION
**Pull request by ghouet**
Closes #4202

### CODE REVIEW

File: lib/util/mime_utils.js [hunk 1]
```diff
@@ -96,6 +96,27 @@ shaka.util.MimeUtils = class {
...
   }
 
+  /**
+   * Get the codec from a codec string, ignoring differences in base sample types declared in the fourCC.
+   *
+   * @param {string} codecString
+   * @return {string}
+   */
+  static getNormalizedCodec(codecString) {
+    switch (shaka.util.MimeUtils.getCodecBase(codecString)) {
```
Comment (avelad) [inline lib/util/mime_utils.js:106]: Is it possible to do the same for audio? For example: mp4a.40.2, mp4a.40.5, mp4a.40.29 and mp4a.40.42

Comment (avelad) [reply lib/util/mime_utils.js:106]: Related to https://github.com/shaka-project/shaka-player/issues/1567

Comment (ghouet) [reply lib/util/mime_utils.js:106]: Hmm, maybe I am misunderstanding the question but all the codec string you quoted share the same fourCC so there is nothing to normalize, getNormalizedCodec will just return mp4a for all these.

**Review by joeyparrish — CHANGES_REQUESTED** [review]

File: lib/util/mime_utils.js [hunk 2]
```diff
@@ -96,6 +96,28 @@ shaka.util.MimeUtils = class {
...
+      case 'avc1':
+      case 'avc3':
+        return 'avc';
+      case 'hvc1':
+      case 'hev1':
+        return 'hevc';
+      case 'dvh1':
+      case 'dvhe':
+        return 'dovi';
```
[the remark this answers is not in the document]
Comment (ghouet) [reply lib/util/mime_utils.js]: Done

File: lib/util/mime_utils.js [hunk 3]
```diff
@@ -107,13 +107,13 @@ shaka.util.MimeUtils = class {
...
       case 'hvc1':
       case 'hev1':
-        return 'hevc';
+        return 'hevc'; // H265
       case 'dvh1':
       case 'dvhe':
-        return 'dovi';
+        return 'dovi'; // Dolby Vision
     }
     return codecString;
```
Comment (joeyparrish) [inline lib/util/mime_utils.js:118]: Ah, I overlooked this before.  For codecs that aren't in the map, we should return the base, not the full codec string.  Can you put that base codec in a local variable, switch on that, and then return the base here instead of the full thing?

**Review by joeyparrish — CHANGES_REQUESTED** [review]

File: lib/util/mime_utils.js (hunk 1 above)
Comment (avelad) [reply lib/util/mime_utils.js:107]: @joeyparrish what do you think?

Comment (joeyparrish) [reply lib/util/mime_utils.js:107]: For mp4a.*, the result of getCodecBase is always "mp4a".  Is there some further mapping needed?

Or are you saying that those mp4a variants are actually mutually incompatible, and so should be mapped to different values here?

Comment (avelad) [reply lib/util/mime_utils.js:107]: the question is whether the decoder is the same and is compatible. if it is not compatible, even if they are aac, it should be prohibited….

Comment (joeyparrish) [reply lib/util/mime_utils.js:107]: Yeah, okay, I get it now.  According to https://chromium.googlesource.com/chromium/src/media/+/master/base/mime_util_internal.cc, mp4a could refer to any of AAC, MP3, XHE AAC, AC3, EAC3, DTS, or DTSXP2.  I'm not sure if AAC/XHEAAC or DTS/DTSXP2 or AC3/EAC3 are compatible (use the same decoder).

If we know what is needed here (I don't know for sure), we can add mappings for audio now.  If not, we can merge this for video and follow up later for mp4a audio.

Comment (avelad) [reply lib/util/mime_utils.js:107]: Maybe related to https://github.com/shaka-project/shaka-player/issues/1528

Comment (ghouet) [reply lib/util/mime_utils.js]: Interesting, maybe we do need a codec enum like theirs (MimeUtil::*).
Let me know if you want to merge this as is, and I can improve this method in a follow up change.

**Review by joeyparrish — DISMISSED** [review]

File: lib/util/mime_utils.js (hunk 1 above)
Comment (joeyparrish) [reply lib/util/mime_utils.js]: It will be important to figure out which mp4a variants use what decoder.

So far it seems that mp3 is obvious and independent, XHE-AAC is _probably_ the same decoder as AAC, and I'm less sure about whether AC3 decoder == EAC3 decoder or DTS decoder == DTSXP2 decoder.  I asked someone in Chrome Media and they weren't sure either.  Those enums may have been added to Chrome for Cast, so I'm reaching out to some folks who work on media for the Cast platform.

Once we have an answer, the change will be trivial to make.  So let's hold this PR briefly until we can fix both audio and video.

Comment (ghouet) [reply lib/util/mime_utils.js]: Updated the PR with the changes we discussed, PTAL.

File: lib/util/mime_utils.js [hunk 4]
```diff
@@ -96,6 +96,55 @@ shaka.util.MimeUtils = class {
...
+      case base === 'mp4a' && profile === '40.2':
+      case base === 'mp4a' && profile === '40.02':
+      case base === 'mp4a' && profile === '40.5':
+      case base === 'mp4a' && profile === '40.05':
+      case base === 'mp4a' && profile === '40.29':
+        return 'mpeg4_aac';
+      case base === 'mp4a' && profile === '40.42':
+        return 'mpeg4_xhe_aac'; // Extended HE-AAC
+      case base === 'mp4a' && profile === 'a5':
+        return 'ac-3'; // Dolby Digital
```
Comment (avelad) [inline lib/util/mime_utils.js:128]: I have doubts here, because this would imply that we can adapt between mp4/ac-3 and mp4/mp4a.a5 and I don't know if this is viable or not...

Comment (avelad) [reply lib/util/mime_utils.js:128]: Same for ec-3, dtsx and dtsc

Comment (ghouet) [reply lib/util/mime_utils.js]: I removed these codecstring since we don't know if shaka would play them together. We can always add them later if we ever encounter mp4a.?? ac-3/ec-3 and find that browsers can transition from one to another.

File: lib/util/mime_utils.js [hunk 5]
```diff
@@ -96,6 +96,47 @@ shaka.util.MimeUtils = class {
...
+      case base === 'mp4a' && profile === '6b':
+        return 'mp3';
+      case base === 'mp4a' && profile === '40.2':
+      case base === 'mp4a' && profile === '40.02':
+      case base === 'mp4a' && profile === '40.5':
+      case base === 'mp4a' && profile === '40.05':
+      case base === 'mp4a' && profile === '40.29':
+        return 'mpeg4_aac';
+      case base === 'mp4a' && profile === '40.42':
+        return 'mpeg4_xhe_aac'; // Extended HE-AAC
```
[the remark this answers is not in the document]
Comment (ghouet) [reply lib/util/mime_utils.js:126]: Is it true the other way though, what if the decoder supports AAC but not XHE-AAC?

[the remark this answers is not in the document]
Comment (joeyparrish) [reply lib/util/mime_utils.js]: It's fine, because we filter streams individually before this point.  If there's no XHE-AAC decoder, we'll never try to connect XHE-AAC streams with anything else, because they'll be removed as unplayable.

The only way normalizing both as AAC would be a problem would be if there were two separate AAC decoders.  But that wouldn't make sense.

File: lib/util/mime_utils.js [hunk 6]
```diff
@@ -121,9 +121,17 @@ shaka.util.MimeUtils = class {
       case base === 'mp4a' && profile === '40.5':
       case base === 'mp4a' && profile === '40.05':
       case base === 'mp4a' && profile === '40.29':
-        return 'mpeg4_aac';
+        return 'aac';
       case base === 'mp4a' && profile === '40.42':
-        return 'mpeg4_xhe_aac'; // Extended HE-AAC
+        return 'xhe_aac'; // Extended HE-AAC
```
Comment (joeyparrish) [inline lib/util/mime_utils.js:126]: Call this 'aac', please, and group the 'aac' cases together.

**Review by joeyparrish — CHANGES_REQUESTED** [review]

File: lib/util/mime_utils.js (hunk 4 above)
Comment (avelad) [reply lib/util/mime_utils.js:126]: I keep seeing this, maybe you forgot to push?

Comment (avelad) [reply lib/util/mime_utils.js:126]: oh sorry :(

**Review by joeyparrish — APPROVED** [review]
