### PR TITLE
fix(media): Fix region checking in livestreams

### LINKED ISSUE #5213: Timed metadata are raised all at once when loading a Live DASH DAI stream in a middle of an ad break (4.3.6)
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes. I found [this issue from 2020](https://github.com/shaka-project/shaka-player/issues/2716), but:
* This issue was only reproducible after a long period of streaming (20, 30 minutes), while I'm experiencing it immediately.
*  I'm using a more recent version of shaka.

**What version of Shaka Player are you using?**
4.3.6 and 2.3.7 (on the DAI Video Suite Inspector)

**Can you reproduce the issue with our latest release version?**
Yes (4.3.6).

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
I first experienced the issue on a custom app using the DAI API.
I then reproduced it on the DAI IMA HTML5 Video Suite Inspector.

**If custom app, can you reproduce the issue using our demo app?**
Yes, using the DAI IMA HTML5 Video Suite Inspector.

**What browser and OS are you using?**
Mac OS 13.3.1 / Chrome 112.0.5615.137 (Official Build) (x86_64)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
URI: https://dai.google.com/linear/dash/pa/event/PSzZMzAkSXCmlJOWDmRj8Q/stream/f61416c6-50b8-40df-9c3f-3cb1c312975a:BRU/manifest.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
No specific configuration is added to the default.

**What did you do?**

1. Visit https://googleads.github.io/googleads-ima-html5-dai/vsi/
2. Enter this asset key PSzZMzAkSXCmlJOWDmRj8Q (official sample LIVE DASH) and select *dash*
3. Click on load. You don't need to start playing the stream.
4. You should land in a middle of an ad break to reproduce issue. If not, reproduce step 3 until you do.

**What did you expect to happen?**

Timed metadata events should be fired progressively, as they are being raised in the stream.

**What actually happened?**

A bunch of events are raised all at once when the stream is loaded (not played):

```

Stream event: streamInitialized
Stream event: loaded
Stream ID: f61416c6-50b8-40df-9c3f-3cb1c312975a:BRU
Stream event: adBreakStarted
Stream event: started
Stream event: firstquartile
Stream event: midpoint
Stream event: thirdquartile
Stream event: complete
Stream event: started
```

### PR DESCRIPTION
**Pull request by theodab**
In some cases, in a livestream situation, the region observer's poll method ends up being called before the media time is set to the live edge. This does not happen every time; it's likely based on the exact time it takes the player to start playing. When this does happen, it leads to the region observer "skipping" over every region between time=0 and the live head, as it erroneously believes that it has actually played through all of that time. This could result in confusion for applications that are relying on region data.

This change modifiers the region observer so that it does not start examining regions until the time gets past 0 seconds, except in the case of VOD.

Closes #5213

### CODE REVIEW

File: lib/media/region_observer.js [hunk 1]
```diff
@@ -121,6 +132,13 @@ shaka.media.RegionObserver = class extends shaka.util.FakeEventTarget {
   /** @override */
   poll(positionInSeconds, wasSeeking) {
     const RegionObserver = shaka.media.RegionObserver;
+    if (this.startsPastZero_ && positionInSeconds == 0) {
+      // Don't stack checking regions until the timeline has begun moving.
```
Comment (joeyparrish) [inline lib/media/region_observer.js:136]: s/stack/start/ ?

**Review by joeyparrish — COMMENTED** [review]
Looks good otherwise

File: lib/media/region_observer.js (hunk 1 above)
Comment (theodab) [reply lib/media/region_observer.js]: Whoops. Thanks for pointing that out!

**Review by joeyparrish — APPROVED** [review]
