### PR TITLE
fix: Mixed clear/encrypted playback on Safari MSE

### LINKED ISSUE #8335: mixed encrypted/clear fairplay audio content fails on append
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

Yes

**What version of Shaka Player are you using?**

4.10

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Safari 18.3

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Using the public fairplay source and another public hls source, I spliced the two together, using a disco tag, for test content.
https://friendly-creponne-991405.netlify.app/mixed-fairplay.m3u8 - encrypted followed by clear
https://friendly-creponne-991405.netlify.app/fairplay-mixed.m3u8 - clear followed by encrypted

https://fps.ezdrm.com/api/licenses/b99ed9e5-c641-49d1-bfa8-43692b686ddb - license server url

https://fps.ezdrm.com/demo/video/eleisure.cer - certificate server url

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**

```js
{
  "streaming": {
    "useNativeHlsForFairPlay": false
  },
}
```
Adding `manifest.disableAudio` makes playback work.
```js
{
  "manifest": {
    "disableAudio": true
  },
  "streaming": {
    "useNativeHlsForFairPlay": false
  },
}
```

**What did you do?**

Play one of the above streams and wait for shaka to start appending the opposite type of what is currently playing.

**What did you expect to happen?**
The append should succeed and playback should continue.

**What actually happened?**

Shaka throws a 3016 error on append, saying media failed to decode.
If I disable the audio stream, then the append succeeds and playback continues across the discontinuity.

**Are you planning to send a PR to fix it?**
I'll continue looking at it, but any help would be greatly appreciated as I haven't been able to find anything obviously wrong here.

### PR DESCRIPTION
**Pull request by tykus160**
Fixes #8335

### CODE REVIEW

File: lib/media/content_workarounds.js [hunk 1]
```diff
@@ -128,9 +129,13 @@ shaka.media.ContentWorkarounds = class {
...
       modifiedInitSegment = ContentWorkarounds.insertEncryptionMetadata_(
           modifiedInitSegment, stsdBox, workItem.box, ancestorBoxes,
-          workItem.newType);
+          workItem.newType, encryptionScheme);
     }
 
+    // Uncomment if you want to save the modified init segment to a file, i.e.
+    // to inspect it in external tool.
+    // ContentWorkarounds.saveFile(modifiedInitSegment);
+
```
Comment (avelad) [inline lib/media/content_workarounds.js:138]: Please remove it!

File: lib/media/content_workarounds.js [hunk 2]
```diff
@@ -341,6 +397,19 @@ shaka.media.ContentWorkarounds = class {
...
+   * @param {!BufferSource} data
+   */
+  static saveFile(data) {
+    const downloadLink = /** @type {!HTMLAnchorElement}*/ (
+      document.createElement('a'));
+    downloadLink.href = URL.createObjectURL(new Blob([data]));
+    downloadLink.download = 'modified-init.mp4';
+    downloadLink.click();
+    URL.revokeObjectURL(downloadLink.href);
+  }
```
Comment (avelad) [inline lib/media/content_workarounds.js:412]: Please remove it!

File: lib/media/content_workarounds.js [hunk 3]
```diff
@@ -147,6 +152,44 @@ shaka.media.ContentWorkarounds = class {
     return modifiedInitSegment;
   }
 
+  /**
+   * @param {!BufferSource} mediaSegmentBuffer
+   * @return {!Uint8Array}
+   */
+  static fakeMediaEncryption(mediaSegmentBuffer) {
```
Comment (avelad) [inline lib/media/content_workarounds.js:159]: Please add a unit test for this!

**Review by avelad — CHANGES_REQUESTED** [review]

**Comment by avelad** [comment]
@shaka-bot test

**Review by avelad — APPROVED** [review]

File: lib/media/media_source_engine.js [hunk 4]
```diff
@@ -2141,18 +2140,28 @@ shaka.media.MediaSourceEngine = class {
...
     const encryptionExpected = this.expectedEncryption_.get(contentType);
     const keySystem = this.playerInterface_.getKeySystem();
+    let isEncrypted = false;
+    if (reference && reference.initSegmentReference) {
+      isEncrypted = reference.initSegmentReference.encrypted;
+    }
+    const uri = reference ? reference.getUris()[0] : null;
 
     // If:
     //   1. the configuration tells to insert fake encryption,
```
Comment (avelad) [inline lib/media/media_source_engine.js:2167]: Update the comment

**Comment by avelad** [comment]
@shaka-bot test

File: lib/util/mp4_generator.js [hunk 5]
```diff
@@ -833,7 +833,7 @@ shaka.util.Mp4Generator = class {
    * @private
    */
   frma_(codecs) {
-    const codec = codecs.substring(0, codecs.indexOf('.'));
+    const codec = codecs.split(',')[0];
```
[the remark this answers is not in the document]
Comment (gkatsev) [reply lib/util/mp4_generator.js:836]: There's definitely a bug here, though, maybe the fix here isn't sufficient for all cases.
But in the case that `codecs` is only `mp4a`, the local `codec` variable ends up being `""`. This is the case for the ezdrm stream I used in the issue.

[the remark this answers is not in the document]
Comment (tykus160) [reply lib/util/mp4_generator.js:836]: It was a typo, sorry. Anyway, I pushed it to another PR for better viewability https://github.com/shaka-project/shaka-player/pull/8367

File: test/media/content_workarounds_integration.js [hunk 6]
```diff
@@ -82,7 +82,28 @@ describe('ContentWorkarounds', () => {
...
+          'com.microsoft.playready': 'http://test.playready.microsoft.com/service/rightsmanager.asmx?cfg=(kid:51745386-2d42-56fd-8bad-4f58422004d7,contentkey:UXRThi1CVv2LrU9YQiAE1w==),(kid:26470f42-96d4-5d04-a9ba-bb442e169800,contentkey:JkcPQpbUXQSpurtELhaYAA==)',
+        },
+      })
+      .set('com.apple.fps', {
+        servers: {
+          'com.apple.fps': 'https://fps.ezdrm.com/api/licenses/b99ed9e5-c641-49d1-bfa8-43692b686ddb',
+        },
+        advanced: {
+          'com.apple.fps': {
+            serverCertificateUri: 'https://fps.ezdrm.com/demo/video/eleisure.cer',
```
Comment (avelad) [inline test/media/content_workarounds_integration.js:102]: Please store the certificate locally :)

**Comment by avelad** [comment]
@shaka-bot test

**Comment by tykus160** [comment]
@shaka-bot test

**Comment by tykus160** [comment]
@shaka-bot test

**Comment by avelad** [comment]
@shaka-bot test

File: lib/media/content_workarounds.js [hunk 7]
```diff
@@ -149,6 +150,110 @@ shaka.media.ContentWorkarounds = class {
...
+      const chunk = mediaSegment.subarray(chunkStart, chunkEnd);
+      newSegmentChunks.push(
+          shaka.media.ContentWorkarounds.fakeMediaEncryptionInChunk_(chunk));
+    }
+    return shaka.util.Uint8ArrayUtils.concat(...newSegmentChunks);
+  }
+
+  /**
+   * @param {!Uint8Array} mediaSegment
+   * @return {!Uint8Array}
```
Comment (gkatsev) [inline lib/media/content_workarounds.js:181]: to fix lint error
```suggestion
   * @return {!Uint8Array}
   * @private
```

File: lib/media/content_workarounds.js [hunk 8]
```diff
@@ -149,6 +150,110 @@ shaka.media.ContentWorkarounds = class {
...
+   */
+  static fakeMediaEncryptionInChunk_(mediaSegment) {
```
Comment (gkatsev) [inline lib/media/content_workarounds.js:183]: Might be nice to rename `mediaSegment` to something like `chunk` or `moof` in here, since we aren't getting a full media segment anymore.

**Comment by tykus160** [comment]
@shaka-bot test

File: lib/media/content_workarounds.js (hunk 8 above)
Comment (tykus160) [reply lib/media/content_workarounds.js]: Done!

**Review by avelad — APPROVED** [review]

**Comment by tykus160** [comment]
@shaka-bot test

**Review by avelad — APPROVED** [review]
