### PR TITLE
fix: prevent bad calls to MediaSource.endOfStream

### LINKED ISSUE #5070: An attempt was made to use an object that is not, or is no longer, usable
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.4

**Can you reproduce the issue with our latest release version?**
Presumably

**Can you reproduce the issue with the latest code from `main`?**
n/a

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
n/a

**What browser and OS are you using?**
Chrome, Edge (notably not on Firefox)

**What did you do?**
Check our playback error metrics, and noticed unhandled errors thrown inside of Shaka. The errors are rare, in the magnitude of a handful per (tens of) thousands of plays.

Play a stream

**What did you expect to happen?**
Shaka plays the stream, or throws a Shaka Error.

**What actually happened?**

Shaka crashes with a native ReferenceError `

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.2.6

**Can you reproduce the issue with our latest release version?**
Presumably, need huge volumes of plays to see issue, and cannot take 4.3.X to prod.

**Can you reproduce the issue with the latest code from `main`?**
n/a

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
n/a

**What browser and OS are you using?**
Chrome, Edge (notably not on Firefox)

**What did you do?**
Check our playback error metrics, and noticed unhandled errors thrown inside of Shaka. The errors are rare, in the magnitude of a handful per (tens of) thousands of plays.

Play a stream

**What did you expect to happen?**
Shaka plays the stream, or throws a Shaka Error.

**What actually happened?**

Shaka crashes with a native DOMException `An attempt was made to use an object that is not, or is no longer, usable`

### PR DESCRIPTION
**Pull request by martinstark**
closes #5070

maybe it would make more sense to only call it when the readyState is `'open'`?

### CODE REVIEW

**Review by theodab — APPROVED** [review]

File: lib/media/media_source_engine.js [hunk 1]
```diff
@@ -1041,8 +1041,10 @@ shaka.media.MediaSourceEngine = class {
   async endOfStream(reason) {
     await this.enqueueBlockingOperation_(() => {
       // If endOfStream() has already been called on the media source,
-      // don't call it again.
-      if (this.ended()) {
+      // don't call it again. Also do not call if readyState is
+      // 'closed' (not attached to video element) since it is not a
+      // valid operation.
+      if (this.ended() || this.mediaSource_.readyState === 'closed') {
```
Comment (theodab) [inline lib/media/media_source_engine.js:1047]: Incidentally, the `ended` method also checks the `readyState` of MS.
I considered asking you to change that instead of making the change here, but the `ended` method is used outside of this class so it's probably simpler to keep it as-is.
