### PR TITLE
fix: Fix subtitles not added to DOM region

### LINKED ISSUE #4680: EBU subtitles regression in 4.1.3 - subtitles lost: not added to region
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

Note the coincidental relationship with #4631 on the same stream and same release.

**What link can we use to reproduce this?**
https://v4-1-3-dot-shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;asset=https://otvplayer.nagra.com/demo/content/bbc/bbc_ebu-tt-d_subtitle_fragmented/dash/ondemand/elephants_dream/1/client_manifest-all-minus-1080p.mpd;panel=CUSTOM%20CONTENT;build=uncompiled

**What version of Shaka Player are you using?**
v4.1.3-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

**What did you do?**

1. Play this stream with captions enabled
1. Observe the captions at 2:52 to 2:57

**What did you expect to happen?**
See the captions as follows:
`You have to learn to listen.`
then
`This is not some game.`

i.e. from the following TTML snippet.
```xml
...
            <p begin="00:02:52.00" end="00:02:54.80" xml:id="sub23">
                <span style="s1">You have to learn to listen.</span>
            </p>
            <p begin="00:02:55.84" end="00:02:57.64" xml:id="sub24">
                <span style="s1">This is not some game.</span>
            </p>
...
```

**What actually happened?**

Neither of these were shown, nothing was in this time range.

Note: this can only be reprod by playing the stream through this range uninterruted, if you pause in that region, they can be shown without issue.

Note: I believe this was introduced in #4412

### PR DESCRIPTION
**Pull request by david-hm-morgan**
Proposed fix closes #4680

Reinstate previously removed region elements when next caption finds it is not there: Detect the absence and ensure `updateDOM` is true so its reinstated and the next caption can be shown.

### CODE REVIEW

File: lib/text/ui_text_displayer.js [hunk 1]
```diff
@@ -199,6 +199,19 @@ shaka.text.UITextDisplayer = class {
...
+   * @private
+   */
+  isElementUnderTextContainer_(elemToCheck) {
+    if (elemToCheck == null) {
+      return false;
+    }
+    if (elemToCheck == this.textContainer_) {
+      return true;
+    }
+    return this.isElementUnderTextContainer_(elemToCheck.parentElement);
```
Comment (joeyparrish) [inline lib/text/ui_text_displayer.js:212]: With only one parent element, I think this could be rewritten as a while loop and be slightly more efficient that way.

https://jsbench.me/ suggests it would be 10% faster, though admittedly I did put the target element 100 levels deep in my test case.

Setup:
```js
  const myContainer = document.createElement('div');
  let innerHTML = '<span id="myTarget"></span>';
  for (i = 0; i < 100; i++) {
    innerHTML = `<span>${innerHTML}</span>`;
  }
  myContainer.innerHTML = innerHTML;
  document.body.appendChild(myContainer);
```

Recursive:
```js
function v1(thing, ancestor) {
  if (thing == null) {
    return false;
  }
  if (thing == ancestor) {
    return true;
  }
  return v1(thing.parentElement, ancestor);
}

console.log(v1(myTarget, document.body));
```

Loop:
```js
function v2(thing, ancestor) {
  while (thing != null) {
    if (thing == ancestor) {
      return true;
    }
    thing = thing.parentElement;
  }
  return false;
}

console.log(v2(myTarget, document.body));
```

**Review by joeyparrish — COMMENTED** [review]
I think this is a good fix overall.  Thanks!  If I have permission to edit, I'll make the change I suggested.

**Review by avelad — APPROVED** [review]
