### PR TITLE
fix(HLS): Fix duplicate hinted segments

### LINKED ISSUE #4223: LL-HLS: Preload hinted fragments is played twice sometimes
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.0.0

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
both

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Chrome/Edge windwos

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

Just play a live LL-HLS URL which has preload hint for the latest part.

**What did you expect to happen?**
Playback works fine.

**What actually happened?**

You will occasionally see audio/video repeat and if you see the network trace, the same part is downloaded twice.

Since the preload hinted part has no duration (start/end time are the same) and then when it becomes a regular part sometimes instea of merging the part looks like we are adding twice and downloading twice.

### PR DESCRIPTION
**Pull request by joeyparrish**
Because zero-duration references cause such chaos, ensure that the HLS
parser never produces these.  Preload-hinted segments should use the
target duration for partial segments, and if that required attribute
is missing from the playlist, then preload-hinted segments should be
skipped.

Closes #4223

### CODE REVIEW

File: lib/hls/hls_parser.js [hunk 1]
```diff
@@ -1893,9 +1893,20 @@ shaka.hls.HlsParser = class {
...
           previousReference : partialSegmentRefs[partialSegmentRefs.length - 1];
         const pStartTime = (i == 0) ? startTime : pPreviousReference.endTime;
-        const pDuration = Number(item.getAttributeValue('DURATION'));
-        // A preload hinted partial segment doesn't have duration information,
-        // so its startTime and endTime are the same.
+
+        // If DURATION is missing from this partial segment, use the target
+        // partial duration from the top of the playlist, which is a required
+        // attribute for content with partial segments.
+        const pDuration = Number(item.getAttributeValue('DURATION')) ||
```
Comment (theodab) [inline lib/hls/hls_parser.js:1900]: Technically this approach means that if a manifest has a tag with `DURATION=0`, we will ignore that. But I don't know why someone would want to do that, so it's probably fine to not account for it.

**Review by theodab — APPROVED** [review]

**Comment by avelad** [comment]
@theodab Is it ready to merge?

**Comment by joeyparrish** [comment]
I had some disagreement with the original reporter of the issue via email, but I still believe this is the correct fix, and an important one based on the severity of the issue.  I've informed them via email that we're going ahead with this fix.
