### PR TITLE
fix(DASH): Fix EventStream Elements creation

### LINKED ISSUE #7148: Excessive memory usage for DASH live with EventStream nodes
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes. These issues are related, but the fix added in v4.10.6 does not resolve this case.
https://github.com/shaka-project/shaka-player/issues/6070
https://github.com/shaka-project/shaka-player/issues/6610

**If the problem is related to FairPlay, have you read the tutorial?**

n/a

**What version of Shaka Player are you using?**

4.10.9

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Chrome Version 127.0.6533.100 (Official Build) (arm64)
macOS Ventura v13.6

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**

Can provide private stream via email if needed.
Issue is not as pronounced but is reproducible with this public stream: https://refapp.hbbtv.org/videos/multiperiod_v8.php?drm=0&advert=1&emsg=0&video=v1,v2,v3&audiolang=eng,fin&sublang=eng,fin,swe&mup=2&spd=8.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Only change from default is `manifest.dash.disableXlinkProcessing = true`.

**What did you do?**

Load a Live DASH manifest with a 3hr DVR window (`timeShiftBufferDepth="PT3H0M0S"`) that includes `EventStream` nodes in the manifest.

**What did you expect to happen?**
I expect to see JS Memory usage and GC more in line with earlier versions of Shaka. 

**What actually happened?**

JS Memory grows at a much faster pace in v4.10.9 than in previous versions tested (v4.3.6 and v4.7.15).
```
Chrome Desktop - DASH LTS - JS Memory				
Time	v4.3.6	v4.7.15	v4.10.9	
30min	58MB	30MB	225MB	
60min	76MB	49MB	428MB	
90min	93MB	64MB	548MB	
```
task-manager-shaka-90min copy

 

**Are you planning send a PR to fix it?**
No. We can currently work around this issue by removing `EvenStream` nodes from our manifests and use `InbandEventStream` `emsg` instead. Note the memory improvements when `EvenStream` nodes are filtered from the manifest.

```
Chrome Desktop - DASH LTS - JS Memory - EventStream Filter				
Time	v4.3.6	v4.7.15	v4.10.9	v4.10.9 w/ Filter
30min	47MB	37MB	136MB	23MB
60min	58MB	52MB	258MB	39MB
```
eventstream-filter

---
Here is more detail on what may be contributing.

Our 3 hr DVR manifest includes 50+ `EventStream` nodes with combined thousands of child `Event` nodes. 
In v4.10.9, Memory heap snapshots are showing thousands of `Detached HTMLUnknownElements`, which do not appear in v4.3 or v4.7. 
detached-unknown-shaka-4 10 9

These elements appear to come from `parseEventStream_` when elements are created with `txmlNodeToDomElement`.

parseeventstream-shaka

txmltodom-shaka

### PR DESCRIPTION
**Pull request by tykus160**
Related to #7148 
Does not create parent elements anymore to reduce memory consumption.
Starts to use `createElementNS()` so created elements will keep proper cases for tag names and they won't be anymore of type `HTMLElement`, but `Element`, which should be more lightweight and suitable for our needs.

### CODE REVIEW

File: lib/util/tXml.js [hunk 1]
```diff
@@ -874,9 +874,9 @@ shaka.util.TXml = class {
    * @param {boolean=} doChildren
    * @return {!Element}
    */
-  static txmlNodeToDomElement(node, doParents = true, doChildren = true) {
+  static txmlNodeToDomElement(node, doParents = false, doChildren = true) {
```
Comment (theodab) [inline lib/util/tXml.js:877]: Since this isn't a publicly exported interface, and the one place this is called `doParents` isn't set manually, we can probably just remove the `doParents` and `doChildren` variables entirely. And just remove the `doParents` logic, and make the `doChildren` logic no longer be conditional.

**Review by theodab — CHANGES_REQUESTED** [review]

File: lib/util/tXml.js [hunk 2]
```diff
@@ -874,32 +874,23 @@ shaka.util.TXml = class {
    * @param {boolean=} doChildren
    * @return {!Element}
    */
-  static txmlNodeToDomElement(node, doParents = true, doChildren = true) {
+  static txmlNodeToDomElement(node) {
```
Comment (theodab) [inline lib/util/tXml.js:877]: You need to also update the JSDoc.

**Review by theodab — CHANGES_REQUESTED** [review]

**Review by avelad — APPROVED** [review]

**Review by theodab — APPROVED** [review]
It sounds like this doesn't completely fix the problem, but it at least looks like a good start.

**Comment by zelalami** [comment]
Hello @tykus160
After updating to the latest changes from this PR, I'm encountering an issue related to the createElementNS function. Specifically, I'm getting the following error:

[Failed to execute 'createElementNS' on 'Document': The namespace URI provided ('') is not valid for the qualified name provided ('scte35:Signal').]

This error occurs when parsing the following EventStream section of my DASH manifest:

```
<?xml version="1.0" ?>
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:scte35="urn:scte:scte35:2014:xml+bin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" profiles="urn:mpeg:dash:profile:isoff-live:2011,urn:hbbtv:dash:profile:isoff-live:2012" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" publishTime="2024-08-28T09:27:58Z" minBufferTime="PT6S" type="dynamic" availabilityStartTime="1970-01-01T00:00:00Z" timeShiftBufferDepth="PT1M1.88S" minimumUpdatePeriod="PT6S" suggestedPresentationDelay="PT12S">
	<Period id="1" start="P19963DT9H26M52.407S">
		...
	</Period>
	<Period id="2" start="P19963DT9H27M50.807S">
		...
	</Period>
	<Period id="3" start="P19963DT9H27M54.287S">
		<EventStream schemeIdUri="urn:scte:scte35:2014:xml+bin" timescale="90000">
			<Event presentationTime="0" duration="2700000" id="1">
				<scte35:Signal>
					<scte35:Binary>.....</scte35:Binary>
				</scte35:Signal>
			</Event>
		</EventStream>
	</Period>
</MPD>
```
