### PR TITLE
fix: Avoid stack overflow when stringifying objects

### LINKED ISSUE #7435: RangeError: Maximum call stack size exceeded on Tizen WebView when playing DRM content
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**
Not applicable, as this issue is not related to FairPlay.

**What version of Shaka Player are you using?**
I am using Shaka Player version 4.11.7

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
I am using my own custom app on the Tizen platform.

**If custom app, can you reproduce the issue using our demo app?**
The demo app is not directly available on Tizen, but testing was performed using a content URL from the demo app: https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd

**What browser and OS are you using?**
WebView on Tizen 8.0, SMART-TV. User Agent details: "5.0 (SMART-TV; LINUX; Tizen 8.0) AppleWebKit/537.36 (KHTML, like Gecko) 108.0.5359.1/8.0 TV Safari/537.36"

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Samsung UE65DU7172UXXH, firmware version 1120

**What are the manifest and license server URIs?**
https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**
{}

**What did you do?**
Trying to play content from https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd without DRM configuration.

**What did you expect to happen?**
I expected a player error NO_LICENSE_SERVER_GIVEN (6012)

**What actually happened?**
The error encountered is RangeError: Maximum call stack size exceeded which points to an issue in the method alphabeticalKeyOrderStringify_ of the file shaka-player.ui.debug.js. The same error occurs if DRM settings are present in the configuration even if the content being played does not have DRM (https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd). If I remove DRM settings, then it plays fine.

image

image

This issue seems to stem from v4.4, because v4.3 works fine.

### PR DESCRIPTION
**Pull request by joeyparrish**
Add special case for arrays, for compatibility with frameworks or polyfills that add properties to Array or Array instances.

Add special case for functions, which always contain circular references and are unexpected in this context.  These seem to appear because of the frameworks/polyfills mentioned above.

Move everything to ObjectUtils, since this is extremely generic.

Closes #7435

### CODE REVIEW

**Comment by joeyparrish** [comment]
Reporter on video-dev Slack confirms that this fixes the issue for him!

File: lib/util/object_utils.js [hunk 1]
```diff
@@ -89,4 +89,87 @@ shaka.util.ObjectUtils = class {
...
+   * @return {string}
+   * @private
+   */
+  static objectStringify_(obj) {
+    const keys = [];
+    for (const key in obj) {
+      keys.push(key);
+    }
+    // Alphabetically sort the keys, so they will be in a reliable order.
+    keys.sort();
```
Comment (tykus160) [inline lib/util/object_utils.js:132]: Could be simplified to
```js
const keys = Object.keys(obj).sort();
```

**Review by tykus160 — APPROVED** [review]
Great job!

File: lib/util/object_utils.js (hunk 1 above)
Comment (joeyparrish) [reply lib/util/object_utils.js:132]: for-in includes the prototype chain, but Object.keys doesn't, so it's only equivalent for anonymous objects...  but for the intended use of this, I think that should be fine.

Comment (joeyparrish) [reply lib/util/object_utils.js]: Done.

**Comment by joeyparrish** [comment]
I just made those edits in the GitHub web UI, so I'll be cautious and let the lint & test runs complete before merging.
