### PR TITLE
fix: Fix DRM workaround for Tizen and Xbox with hvc1/hev1 boxes

### LINKED ISSUE #4742: Tizen unable to play clear HVC1 when configured for DRM
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.2.3

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Tizen 

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
UE43TU8505UXXC (Tizen 5.5)

**What are the manifest and license server URIs?**
```xml
<Representation id="dzEgCyCf" bandwidth="2100000" codecs="hvc1.1.6.L120.b0" width="1024" height="576" frameRate="50" sar="1:1" />
```

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Default configuration

**What did you do?**
Attempt to reproduce HVC1 clear content when DRM Widevine servers are configured

**What did you expect to happen?**
```
Forcing fake encryption information in init segment.
Inserting "enca" box into init segment.
Forcing fake encryption information in init segment.
Inserting "encv" box into init segment.
```

**What actually happened?**
```
Forcing fake encryption information in init segment.
Inserting "enca" box into init segment.
Forcing fake encryption information in init segment.
Failed to find boxes needed to fake encryption!
```

### PR DESCRIPTION
**Pull request by ricardo-a-alves-alb**
fixes #4742

### CODE REVIEW

File: lib/media/content_workarounds.js [hunk 1]
```diff
@@ -69,6 +69,12 @@ shaka.media.ContentWorkarounds = class {
         })
         .fullBox('encv', onEncryptionMetadataBox)
         .fullBox('enca', onEncryptionMetadataBox)
+        .fullBox('hvc1', (box) => {
```
Comment (avelad) [inline lib/media/content_workarounds.js:72]: Please, add hev1 also

**Review by avelad — CHANGES_REQUESTED** [review]

File: lib/media/content_workarounds.js (hunk 1 above)
Comment (ricardo-a-alves-alb) [reply lib/media/content_workarounds.js:78]: Just pushed a commit to fulfill your request.

Comment (avelad) [reply lib/media/content_workarounds.js:78]: Thanks!

**Review by avelad — APPROVED** [review]
