### PR TITLE
fix: Fix vanishing tracks while offline

### LINKED ISSUE #4408: Resolution disappear if network intermittent
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
v4.1.2

**Can you reproduce the issue with our latest release version?**
Yes.

**Can you reproduce the issue with the latest code from `main`?**
Probably.

**Are you using the demo app or your own custom app?**
Both.

**If custom app, can you reproduce the issue using our demo app?**
Yes.

**What browser and OS are you using?**
Google Chrome.

**What did you do?**
Go to, https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd;adTagUri=https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpod&cmsid=496&vid=short_onecue&correlator=;panel=HOME;build=uncompiled

Select a resolution (818 maybe), then Press `F12` open chrome dev tool, go to network tab and select `Offline`, wait about 20s, now check resolution on player, it all gone (see image below).

**What did you expect to happen?**
Resolution still there.

**What actually happened?**
Resolution disappear.

image

### PR DESCRIPTION
**Pull request by joeyparrish**
Introduced in #4189, as a side-effect of restricting tracks when a
network failure occurs.  We should not trigger such restrictions when
the browser is known to be offline.

Closes #4408

### CODE REVIEW

File: test/player_unit.js [hunk 1]
```diff
@@ -422,7 +422,6 @@ describe('Player', () => {
             dispatchEventSpy.calls.reset();
             player.configure({streaming: {maxDisabledTime}});
             player.setMaxHardwareResolution(123, 456);
-            onErrorCallback(httpError);
```
Comment (JulianDomingo) [inline test/player_unit.js:425]: Just to make sure I understand, was this line moved to the `it()` level since there's now a nested `describe()` scenario that also needs to call `onErrorCallback(httpError)` at the appropriate time in the jasmine test life cycle?

**Review by JulianDomingo — APPROVED** [review]

**Review by theodab — APPROVED** [review]

File: test/player_unit.js (hunk 1 above)
Comment (joeyparrish) [reply test/player_unit.js:425]: Yes.  The original author of these tests put onErrorCallback() in beforeEach().  But since that is the thing which triggers the code under test, it really belongs in the test itself.  The rest can still be considered test setup.

This only became an issue when I wanted to nest another level with different setup.  All setup needs to happen before the code under test is triggered.
