### PR TITLE
fix(DASH): Fix support for multi-mimeType variants

### LINKED ISSUE #6010: DASH + ad insertion: Uncaught exception in promise in 4.7.0
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the problem is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**

4.6.3, 4.7.1

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
n/a

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Chrome/MacOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Can be provided in email if needed

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default demo app

**What did you do?**

Play dash manifest with ad insertion, problem occurs when switching between content and ads

**What did you expect to happen?**
No uncaught exception in the console

**What actually happened?**

Error in the console:
image

The codecs in the array:
image

The error says `MANIFEST.HLS_COULD_NOT_GUESS_CODECS` but HLS is not involved.

Content will continue playing, but the console will fill up with errors.

I didn't see the issue on 4.6.3, but I did see it in 4.7.0, perhaps this commit is a good place to start?
https://github.com/shaka-project/shaka-player/commit/24e32559bff6457aa8a1b356f26d83b6a320b9b2

### PR DESCRIPTION
**Pull request by theodab**
A previous PR, #5950, added support for variants that contain multiple different codecs.
It was supposed to also add support for variants with multiple mimeTypes, but that part didn't work correctly. This reworks a lot of #5950 and #6047, to change how they handle such complicated variants.

This has the side-effect of allowing the stream utils to differentiate between content that has multiple codecs because of type changes, and content that has multiple codecs because of being muxed video+audio.

Fixes #6010

### CODE REVIEW

File: lib/util/stream_utils.js [hunk 1]
```diff
@@ -523,51 +523,69 @@ shaka.util.StreamUtils = class {
...
+    const merge = (a, b) => {
+      if (!a) {
+        return b;
+      } else {
+        const res = shaka.util.ObjectUtils.cloneObject(a);
+        res.supported = a.supported && b.supported;
+        res.powerEfficient = a.powerEfficient && b.powerEfficient;
+        res.smooth = a.smooth && b.smooth;
+        if (!b.keySystemAccess) {
+          res.keySystemAccess = null;
```
Comment (willdharris) [inline lib/util/stream_utils.js:544]: We're getting the `REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE` error because `decodingInfo.keySystemAccess` is `null` for every variant. I think this block is the reason. `res.keySystemAccess` can be set to null here, but never a valid value. If I make this change, it gets us past the `REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE` error.

```suggestion
        res.keySystemAccess = b.keySystemAccess ? b.keySystemAccess : null;
```

**Comment by joeyparrish** [comment]
@theodab, you have a few dozen test failures on every platform.  Can you please fix the tests?

**Comment by joeyparrish** [comment]
Tests are failing consistently with disconnection errors.  If I saw that on one browser, I would chalk it up to a random infrastructure issue.  But it's pretty consistent across platforms.  Is it possible that this PR either crashes a browser or ties up the main thread in JS for long enough that the browser is seen as having "disconnected"?

**Comment by theodab** [comment]
> Tests are failing consistently with disconnection errors. If I saw that on one browser, I would chalk it up to a random infrastructure issue. But it's pretty consistent across platforms. Is it possible that this PR either crashes a browser or ties up the main thread in JS for long enough that the browser is seen as having "disconnected"?

Doing a full test run on my local machine I get:

> Chrome 123.0.0.0 (Mac OS 10.15.7) ERROR
>   Disconnected reconnect failed before timeout of 10000ms (ping timeout)
> Chrome 123.0.0.0 (Mac OS 10.15.7) ERROR
>   Disconnected , because no message in 300000 ms.

So that seems quite possible, yeah.
I wish it'd tell me which test it was timing out during... I guess I'll have to run it again in verbose mode.

**Comment by theodab** [comment]
Okay, it appears that the streaming engine live integration tests crash the browser, so that's the culprit.

**Comment by joeyparrish** [comment]
@theodab has to move to a higher priority issue right now, so I will help debug these tests as soon as I'm available.

**Comment by theodab** [comment]
That should fix the issue that @avelad reported. Now I just need to fix the final test failures.

**Review by avelad — APPROVED** [review]
